### ISSUE TITLE
Add support for multiple clusters in a management domain

### ISSUE THREAD

**Issue by garlicNova** [vmware/powershell-module-for-vmware-cloud-foundation-power-management#41]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

The sample scripts support multiple clusters for a workload domain.

Consider adding support for:
- More than one cluster in a management domain.
- Ability to shutdown/startup a single cluster in a management domain.  

### Use Case(s)

Multiple clusters in a management domain is often common in consolidated architecture.

### Potential Configuration

```powershell
PowerManagement-ManagementDomain.ps1 -server <sddc manager FQDN> -user <SSO admin user> -pass <user password> -sddcDomain <mgmt domain> -vsanCluster <cluster1, cluster2> -Shutdown
```

**Comment by burnsjared0415** [comment]
will pick this up
