### ISSUE TITLE
Add support to return Aria Operations for Logs virtual machine names

### ISSUE THREAD

**Issue by garlicNova** [vmware/powershell-module-for-vmware-cloud-foundation-power-management#42]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add support to return the virtual machine name for Aria Operations for Logs. Generally, the virtual machine names are the hostnames of the nodes' FQDN; however, this is not always the case and is configurable.

### Use Case(s)

For instances where the virtual machine names are not the hostnames of the nodes' FQDN.

### Potential Configuration

If using "VMware Cloud Foundation mode" this could be returned from SDDC Manager with `Get-vRLIServerDetail` from `PowerValidatedSolutions`. However, if not in this mode, it would need to be returned from Aria Lifecycle.

**Comment by burnsjared0415** [comment]
I will pick this up
