### ISSUE TITLE
Add support where Aria Operations collectors / proxies reside in another domain

### ISSUE THREAD

**Issue by garlicNova** [vmware/powershell-module-for-vmware-cloud-foundation-power-management#43]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add support where Aria Operations remote collectors or cloud proxies reside in another domain. 

### Use Case(s)

Add support where Aria Operations remote collectors or cloud proxies reside in another domain, such as a dual-region with collectors / proxies in the second region management domain.

### Potential Configuration

In "VMware Cloud Foundation mode" the collector / proxy nodes location could be returned from SDDC Manager and Aria Lifecycle - or directly from Aria Lifecycle when not in this mode. The collectors / proxies should then be shutdown prior to the cluster.

**Comment by burnsjared0415** [comment]
i can pick this up
