### ISSUE TITLE
Shutdown of a management domain will fail if Aria Operations is not available

### ISSUE THREAD

**Issue by garlicNova** [vmware/powershell-module-for-vmware-cloud-foundation-power-management#44]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-cloud-foundation-power-management/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

v4.5

### PowerShell Version

Windows Powershell 5.1

### PowerCLI Version

v12.x

### Module Version

v1.1.0

### PowerVCF Version

v2.2.0

### Guest Operating System

windows server 2019

### Environment Details

Scripts is called multiple times.  In the moment if MGMT domain shutdown have passed the vROps shutdown step and then stopped during the next run we will stop at the point for shutting vROps cluster since we could not connect to the vROps API.

### Description

The management domain shutdown will stop at the point for shutting down the Aria Operations cluster. If the Aria Operations cluster is already in a powered off state, the script will try to connect to the Aria Operations API.  This prevents the completing the script, since this error is not skipable.

The script should check if Aria Operations is running before attempting to connect to to it's API.

### Error or Debug Output

The script failed to complete due to unable connect to Aria Operations API

### Expected Behavior

The script continues after confirming the cluster is powered off. 

### Actual Behavior

The script failed to complete due to being unable connect to Aria Operations API.

### Steps to Reproduce

1. Initiate management domain shutdown and quit after the script have passed the Aria Operations shutdown step.
2. Re-run management domain shutdown and the script should fail/stop at the point for shutting Aria Operations cluster since it cannot connect to the Aria Operations API.

**Comment by burnsjared0415** [comment]
Is this still needed? vROPS was removed from the Script, I am adding back with multiple site
