### ISSUE TITLE
When vSAN File Services is enabled the workload domain shutdown attempts to shutdown the service nodes

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/powershell-module-for-vmware-cloud-foundation-power-management#48]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-cloud-foundation-power-management/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5

### PowerShell Version

Windows PowerShell 5.1

### PowerCLI Version

13.0.0

### Module Version

1.1.0

### PowerVCF Version

2.3.0

### Guest Operating System

Windows Server 2019

### Description

When vSAN File Services is enabled on vSAN cluster, the workload domain shutdown script attempts to shutdown the vSAN file service nodes when `shutdowncustomerVM` flag is provided.

As the virtual machines are managed by EAM, the script should not shutdown the virtual machines. 

"vSAN cluster shutdown"/"Restart cluster" process would shutdown/startup them automatically. 

### Error or Debug Output

See screenshot.

### Expected Behavior

Allow EAM to manage the vSAN File Service nodes shutdown process.

### Actual Behavior

The workload domain shutdown script attempt to shutdown the vSAN file service notes when `shutdowncustomerVM` flag is provided.

### Steps to Reproduce

Run the workload domain shutdown script with the `shutdowncustomerVM` flag.

### Screenshots

![image](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-power-management/assets/7771363/d2f148da-8c20-40e7-b7ef-fc2d3d7775aa)

### References

Ref : https://vmware.slack.com/archives/C037S8SAT9A/p1668177125983159

**Comment by burnsjared0415** [comment]
will pick up
