### ISSUE TITLE
Add support to determine Tanzu virtual machine name through WCP and vCenter Server

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/powershell-module-for-vmware-cloud-foundation-power-management#54]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently we are using "VCF/VVS" name standarts to identify the Tanzu VMs, some of those VMs will have different names in customer environment (*-tkc01-.*).

### Use Case(s)

Do not rely on hard-coded names for components that contain user inputs.

### Potential Configuration

The virtual machine names are not random and are connected in some way with the data that user provides during Tanzu configuration. There could be an API that will returns this information.

**Comment by burnsjared0415** [comment]
I can pick this up if you are ok with

**Comment by burnsjared0415** [comment]
today the code does not supported Tanzu enabled clusters, here is the command 
```powershell
    # Check if Tanzu is enabled in WLD
            $status = Get-TanzuEnabledClusterStatus -server $vcServer.fqdn -user $vcUser -pass $vcPass -cluster $cluster.name
            if ($status -eq $True) {
                Write-PowerManagementLogMessage -Type ERROR -Message "Currently workload domains with vSphere with Tanzu are not supported. Exiting."
            }
```
