### ISSUE TITLE
Add support to shutdown NSX components once no virtual machines are running on overlays

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/powershell-module-for-vmware-cloud-foundation-power-management#56]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add a check if there are virtual machines running on NSX overlay networks, before stopping NSX components. 

### Use Case(s)

Since we use Aria Lifecycle to shutdown the Aria components, we need access to Aria Lifecycle but this access is terminated once we stop the NSX Edges in the management domain.

This is covered to some extend with the "check for running VMs" and multi-cluster support implementations.

### Potential Configuration

Check if there are some user or management virtual machines running in overlay.

**Comment by burnsjared0415** [comment]
i can pick this up if you want

**Comment by burnsjared0415** [comment]
scope is for management domain
